[build]
  command = "npm run build"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_SUPABASE_URL"
  NEXT_PUBLIC_SITE_URL = "https://quadencode.netlify.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"
